services:
  - type: web
    name: ai-cohere-app
    env: python
    plan: standard
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: COHERE_API_KEY
        sync: false  # 請於 Render 後台設定
